### ISSUE TITLE
syntax error on debian 9 with Python v 3.5.3

### ISSUE THREAD

**Issue by ralfhauser** [paulhoule/gastrodon#7]
in jupyter notebook, got the below error when doing

import pandas as pd
import io
import numpy as np
from urllib.request import urlopen
import json
from math import *
from platform import python_version
print("Python v "+python_version())
from gastrodon import RemoteEndpoint,QName,ttl,URIRef,inline
from matplotlib import pyplot

<<
Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-11-dadd341f35f9>", line 9, in <module>
    from gastrodon import RemoteEndpoint,QName,ttl,URIRef,inline

  File "/usr/local/lib/python3.5/dist-packages/gastrodon/__init__.py", line 136
    kwargs:Dict={}
          ^
SyntaxError: invalid syntax
>>

Any hints ?

**Comment by cknoll** [comment]
Background: As far as I know so called typing hints like `kwargs:Dict={}` were introduced in Python 3.6. They (normally) have no algorithmic consequence but help IDEs to give useful auto-completion proposals and type warnings during development.

As `setup.py` states this package requires at least Python 3.7.

In case anybody uses an OS where the Python version is too old, I would recommend using miniconda, e.g. from 

https://repo.continuum.io/miniconda/ or directly from https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh.

Then one can create environments for different (and newer) python versions (which is imho not possible with packages like [venv](https://docs.python.org/3/library/venv.html) or [virtualenv](https://virtualenv.pypa.io/en/latest/index.html)).


I would opt for closing this issus with label `wontfix`.
